services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app 
    working_dir: /usr/src/app/frontend
    command: yarn dev
    ports:
      - "3000:3000"
      - "5173:5173"
      - "6006:6006"