services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}  